set windows-shell := ["pwsh.exe", "-c"]
binary := "../../target/debug/pulumi_wasm_runner"
wasm := "../../target/wasm32-wasi/debug/pulumi/pulumi_wasm_example_dependencies.wasm"

run:
    {{binary}} run --wasm {{wasm}}

[windows]
local-test:
    #!pwsh
    cargo build -p pulumi_wasm_runner
    cargo run -p cargo-pulumi
    $env:PULUMI_CONFIG_PASSPHRASE=" "
    pulumi destroy -y
    pulumi up -y