set windows-powershell := true

@default: build

[windows]
build:
    pulumi plugin rm language wasm -y
    go build
    pulumi plugin install language wasm 1.0 --file ./pulumi-language-wasm.exe

[linux]
[macos]
build:
    pulumi plugin rm language wasm -y
    go build
    pulumi plugin install language wasm 1.0 --file ./pulumi-language-wasm

fmt:
    go fmt .