[package]
name = "pulumi_wasm_random"
version = "4.15.0-0.0.0-NIGHTLY-2d9495b"
edition = "2021"

[dependencies]
wit-bindgen.workspace = true
pulumi_wasm_rust.workspace = true
serde.workspace = true
automod.workspace = true

[package.metadata.pulumi]
related_crate = "pulumi_wasm_random_provider"
