use anyhow::Error;
use pulumi_wasm_provider_random_rust::random::{create_random_string, RandomStringArgs};
use pulumi_wasm_rust::output::Output;
use pulumi_wasm_rust::pulumi_main;

// Causes compilation errors
// Generated by cargo-component
// mod bindings;

#[pulumi_main]
fn test_main() -> Result<(), Error> {
    let length: Output<i32> = Output::new(&12).map(|i: i32| i * 3);
    let _ = create_random_string(RandomStringArgs {
        name: "test",
        length,
    });
    Ok(())
}
